Feature/account and storage access list internal
LimeChain/hedera-protobufs-java pull request #10
Opened 2021-10-28 12:29 UTC by tdermendzhievv

2021-10-28 12:48 UTC, Daniel-K-Ivanov requested changes
We should add protobuf documentation for the newly added properties

2021-10-28 12:48 UTC, Daniel-K-Ivanov commented on src/main/proto/access_list_entry.proto
> +  oneof obtainers {
I think that a better name would be `entity` instead of `obtainers`

2021-10-28 12:48 UTC, Daniel-K-Ivanov commented on src/main/proto/access_list_entry.proto
> +    ContractID warmUpContractID = 2;
I think that `warmUp` is a unnecessary prefix. We can use `accountID` and `contractID` directly

2021-10-28 12:48 UTC, Daniel-K-Ivanov commented on src/main/proto/access_list_entry.proto
> +message AccessListEntry {
I think that it would be better to include this message in the `basic-types` proto file instead of having a separate proto. Usually we do not have a separate proto unless it is a standalone operation f.e

2021-10-29 06:29 UTC, stoqnkpL reviewed
@Daniel-K-Ivanov  Do you think it makes sense to use uint32 instead of bytes for the storageKeys? This way:
- dev EX would be improved, since we won't have to input positions as bytes
- we won't have to check the input for overflowing

2021-11-01 08:47 UTC, Daniel-K-Ivanov commented
> @Daniel-K-Ivanov Do you think it makes sense to use uint32 instead of bytes for the storageKeys? This way:
> 
> * dev EX would be improved, since we won't have to input positions as bytes
> * we won't have to check the input for overflowing

We will need to use `bytes`. `uint32` won't work. We need `uint256` which does not exist in the grpc protobufs

2021-11-01 08:48 UTC, Daniel-K-Ivanov requested changes

2021-11-01 08:48 UTC, Daniel-K-Ivanov commented on src/main/proto/basic_types.proto
> +message AccessListEntry {
We need to add documentation for the new `message`

2021-11-01 08:48 UTC, Daniel-K-Ivanov commented on src/main/proto/contract_call.proto
> +    repeated AccessListEntry accessList = 5;
Documentation needs to be added

2021-11-01 08:48 UTC, Daniel-K-Ivanov commented on src/main/proto/contract_call_local.proto
> +    repeated AccessListEntry accessList = 6;
Documentation needs to be added

2021-11-01 08:48 UTC, Daniel-K-Ivanov commented on src/main/proto/contract_create.proto
> +    repeated AccessListEntry accessList = 14;
Documentation needs to be added

2021-11-02 14:10 UTC, stoqnkpL requested changes

2021-11-02 14:10 UTC, stoqnkpL commented on src/main/proto/basic_types.proto
> + * transaction in order to spend gas.
```suggestion
 * transaction in order to save gas.
```

2021-11-02 14:10 UTC, stoqnkpL commented on src/main/proto/basic_types.proto
> +     * The address of the account that should be "warm up"/loaded in the EVM
```suggestion
     * The address of the account that should be "warmed up"/loaded in the EVM
```

2021-11-02 14:10 UTC, stoqnkpL commented on src/main/proto/basic_types.proto
> +     * The address of the smart contract that should be "warm up"/loaded in the EVM
```suggestion
     * The address of the smart contract that should be "warmed up"/loaded in the EVM
```

2021-11-02 14:10 UTC, stoqnkpL commented on src/main/proto/basic_types.proto
> +   * The storage keys of the smart contract that should be "warm up"/loaded in the EVM
```suggestion
   * The storage keys of the smart contract that should be "warmed up"/loaded in the EVM
```

2021-11-02 14:10 UTC, stoqnkpL commented on src/main/proto/contract_call.proto
> +     * List with accounts or smart contracts and storage keys that should be "warm up"/loaded in the EVM
```suggestion
     * List with accounts or smart contracts and storage keys that should be "warmed up"/loaded in the EVM
```

2021-11-02 14:10 UTC, stoqnkpL commented on src/main/proto/contract_call_local.proto
> +     * List with accounts or smart contracts and storage keys that should be "warm up"/loaded in the EVM
```suggestion
     * List with accounts or smart contracts and storage keys that should be "warmed up"/loaded in the EVM
```

2021-11-02 14:10 UTC, stoqnkpL commented on src/main/proto/contract_create.proto
> +     * List with accounts or smart contracts and storage keys that should be "warm up"/loaded in the EVM
```suggestion
     * List with accounts or smart contracts and storage keys that should be "warmed up"/loaded in the EVM
```

2021-11-02 14:10 UTC, stoqnkpL commented on src/main/proto/response_code.proto
> +   * Evm tx processor should confirm that provided storage key is not bigger than 32 bytes
I suggest not to mention the EvmTxProcessor directly and just explain that this response code is related to a precheck for storage keys and they should not be larger than 32 bytes

2021-11-02 14:23 UTC, stoqnkpL approved these changes

2021-11-02 15:59 UTC, merged